#!/bin/bash

#DEBHELPER#

# postinst script for udev-modified-init
# replace script if been removed

#set -e

case "$1" in
  install|upgrade) if [ ! -e /etc/init.d/udev ]; then
  						cp /usr/share/udev-modified-init/udev /etc/init.d/udev
  						update-rc.d udev defaults
  					fi
				
                   ;;

                *) :
                   ;;
esac 

exit 0
